#pragma once
// Storage Fabric version macros.
#define STORAGEFABRIC_VERSION_MAJOR 1
#define STORAGEFABRIC_VERSION_MINOR 0
#define STORAGEFABRIC_VERSION_PATCH 0
#define STORAGEFABRIC_VERSION_STRING "1.0.0"
